import type { Metadata } from "next"
import { Playfair_Display } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import ReduxProvider from "@/components/ReduxProvider"
import ModalManager from "@/components/modals/ModalManager"
import AutoOpenModal from "@/components/AutoOpenModal"
import { OrganizationSchema, WebsiteSchema } from "@/components/StructuredData"

const playfair = Playfair_Display({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-playfair",
})

export const metadata: Metadata = {
  metadataBase: new URL('https://quaysotrungthuong.vn'),
  title: {
    default: "GalaVote - Hệ thống Bình chọn Sự kiện Chuyên Nghiệp",
    template: "%s | GalaVote"
  },
  description: "Nền tảng bình chọn sự kiện hàng đầu Việt Nam. Check-in QR Code, Vote realtime, Lucky Draw và Analytics chuyên nghiệp cho Gala, Company Party, Year-end Party. Minh bạch, dễ sử dụng, được tin tưởng bởi hàng trăm sự kiện.",
  keywords: [
    'hệ thống bình chọn',
    'bình chọn sự kiện',
    'event voting',
    'gala vote',
    'check-in qr code',
    'quay số trúng thưởng',
    'lucky draw',
    'company party',
    'year-end party',
    'hệ thống vote realtime',
    'bình chọn online',
    'quản lý sự kiện',
    'event management',
    'voting system Vietnam'
  ],
  authors: [{ name: 'Code4Change.tech', url: 'https://code4change.tech' }],
  creator: 'Code4Change.tech',
  publisher: 'GalaVote',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'vi_VN',
    url: 'https://quaysotrungthuong.vn',
    siteName: 'GalaVote',
    title: 'GalaVote - Hệ thống Bình chọn Sự kiện Chuyên Nghiệp',
    description: 'Nền tảng bình chọn sự kiện hàng đầu Việt Nam. Check-in QR Code, Vote realtime, Lucky Draw và Analytics cho sự kiện của bạn.',
    // Images will be automatically generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'GalaVote - Hệ thống Bình chọn Sự kiện Chuyên Nghiệp',
    description: 'Nền tảng bình chọn sự kiện hàng đầu Việt Nam với Check-in QR Code, Vote realtime và Lucky Draw.',
    creator: '@galavote',
    // Images will be automatically generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Icons will be automatically generated by icon.tsx
  // Manifest will be automatically generated by manifest.ts
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
  },
  alternates: {
    canonical: 'https://quaysotrungthuong.vn',
  },
  category: 'technology',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi">
      <head>
        <OrganizationSchema />
        <WebsiteSchema />
      </head>
      <body className={`${playfair.variable} font-sans`}>
        <ReduxProvider>
          <AutoOpenModal />
          {children}
          <ModalManager />
          <Toaster position="top-center" richColors />
        </ReduxProvider>
      </body>
    </html>
  )
}
