import type { Metadata } from "next"
import { Playfair_Display } from "next/font/google"
import "./globals.css"
import { Toaster } from "sonner"
import { Toaster as RadixToaster } from "@/components/ui/toaster"
import ReduxProvider from "@/components/ReduxProvider"
import ModalManager from "@/components/modals/ModalManager"
import AutoOpenModal from "@/components/AutoOpenModal"
import { OrganizationSchema, WebsiteSchema } from "@/components/StructuredData"

const playfair = Playfair_Display({
  subsets: ["latin", "vietnamese"],
  weight: ["400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-playfair",
})

export const metadata: Metadata = {
  metadataBase: new URL('https://bright4event.com'),
  title: {
    default: "Bright4Event - Nền tảng tổ chức sự kiện thông minh All-in-One",
    template: "%s | Bright4Event"
  },
  description: "Nền tảng tổ chức sự kiện toàn diện, chuyên nghiệp. Từ Check-in QR, Màn hình chào mừng, Live Voting, Quay số trúng thưởng đến Analytics realtime — tất cả trong một nền tảng duy nhất. Giúp doanh nghiệp tổ chức sự kiện hiện đại, hiệu quả và ấn tượng.",
  keywords: [
    'tổ chức sự kiện',
    'phần mềm sự kiện',
    'event platform',
    'nền tảng sự kiện all-in-one',
    'hệ thống bình chọn',
    'bình chọn sự kiện',
    'event voting',
    'gala vote',
    'check-in qr code',
    'quét qr sự kiện',
    'màn hình chào mừng',
    'welcome screen',
    'countdown sự kiện',
    'quay số trúng thưởng',
    'lucky draw',
    'company party',
    'year-end party',
    'hệ thống vote realtime',
    'bình chọn online',
    'quản lý sự kiện',
    'event management',
    'analytics sự kiện',
    'livestream integration',
    'mini game sự kiện',
    'voting system Vietnam',
    'bright4event',
    'hệ thống sự kiện chuyên nghiệp',
    'bình chọn trực tuyến',
    'vote online',
    'event tech platform'
  ],
  authors: [{ name: 'Bright4Event', url: 'https://bright4event.com' }],
  creator: 'Bright4Event',
  publisher: 'Bright4Event',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  openGraph: {
    type: 'website',
    locale: 'vi_VN',
    url: 'https://bright4event.com',
    siteName: 'Bright4Event',
    title: 'Bright4Event - Nền tảng tổ chức sự kiện thông minh All-in-One',
    description: 'Từ Check-in, Voting đến Quay số trúng thưởng và Analytics. Bright4Event giúp doanh nghiệp tổ chức sự kiện hiện đại, hiệu quả và ấn tượng.',
    // Images will be automatically generated by opengraph-image.tsx
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Bright4Event - Nền tảng tổ chức sự kiện thông minh All-in-One',
    description: 'Check-in QR, Màn hình chào mừng, Live Voting, Lucky Draw, Livestream & Analytics realtime — tất cả trong một nền tảng.',
    creator: '@Bright4Event',
    // Images will be automatically generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  // Icons will be automatically generated by icon.tsx
  // Manifest will be automatically generated by manifest.ts
  verification: {
    google: 'your-google-verification-code',
    yandex: 'your-yandex-verification-code',
  },
  alternates: {
    canonical: 'https://bright4event.com',
  },
  category: 'technology',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi">
      <head>
        <OrganizationSchema />
        <WebsiteSchema />
      </head>
      <body className={`${playfair.variable} font-sans`}>
        <ReduxProvider>
          <AutoOpenModal />
          {children}
          <ModalManager />
          <Toaster position="top-center" richColors />
          <RadixToaster />
        </ReduxProvider>
      </body>
    </html>
  )
}
